### ISSUE TITLE
Wrong form being used to display/edit case activities

### ISSUE THREAD

**Issue by demeritcowboy** [compucorp/uk.co.compucorp.civicase#150]
Hi, I was trying out this extension and noticed that the non-case activity form is being used to display case activities. This leads to at least a few things:

1) Edit button links to the non-case form.
2) Medium field disappears. (Encounter medium - the one beside Location on the new case activity form).
3) Label for the "Reported By" field reverts to "With Contact" instead of "Reported By".
4) Can't send copy when editing.

**Comment by demeritcowboy** [comment]
Ok thanks.

**Comment by shitijg** [comment]
Fixed: https://github.com/compucorp/uk.co.compucorp.civicase/pull/154
