### ISSUE TITLE
Singleton activity warning has wrong url

### ISSUE THREAD

**Issue by demeritcowboy** [compucorp/uk.co.compucorp.civicase#151]
- On manage case, click the add new button at far right.
- Choose an activity type that already exists on the case and is a singleton (max instances = 1).
- It will properly give you the warning that the singleton activity already exists, and provide a link to edit the existing one, but the link has id=0 instead of the actual activity id.

**Comment by shitijg** [comment]
Thanks @demeritcowboy - we'll fix this in the next release too.

**Comment by shitijg** [comment]
Fixed in https://github.com/compucorp/uk.co.compucorp.civicase/pull/155
