### ISSUE TITLE
Submenu issue on firefox

### ISSUE THREAD

**Issue by demeritcowboy** [compucorp/uk.co.compucorp.civicase#152]
This doesn't come up on Chrome, so must be something different about Firefox.

Under the add new button at far right on manage case, the Add Activity and Add Timeline submenu choices will pop out a submenu, but as soon as you move the mouse to choose one of the items, the menu disappears.

It's a fun game for the first 5 or 6 tries then stops being fun (hehe).

**Comment by shitijg** [comment]
Hi @demeritcowboy 

Thanks for raising this, sorry this didn't make the cut for the release today.

I've added this to my backlog and this should be a part of the next release (mid-feb)

Best,
Shitij

**Comment by demeritcowboy** [comment]
No worries. Thanks for the update.

**Comment by reneolivo** [comment]
Fixed by #383
