### ISSUE TITLE
Unknown path error

### ISSUE THREAD

**Issue by bhahumanists** [compucorp/uk.co.compucorp.civicase#305]
With 1.0.0 beta1, 5.19.2 and WP 5.3, I get an "Unknown path" error when trying to load any CiviCase angular pages. PHP error log says:

file_get_contents(): Filename cannot be empty in /data/vhosts/humanism.org.uk/wp-content/plugins/civicrm/civicrm/Civi/Angular/Page/Modules.php on line 107

I can dig into it, but just wondering if this is a known issue.

**Comment by shitijg** [comment]
Thanks for your message. 

We did test the beta version before tagging it and it all seemed to work. Have you tried clearing both the Civicrm and WP caches?

I also found a couple of similar issues: 
https://stackoverflow.com/questions/37835803/filename-cannot-be-empty
https://forum.civicrm.org/index.php%3Ftopic=35734.0.html

Hope one of these helps to resolve your issue :) 

Best,
Shitij

**Comment by bhahumanists** [comment]
This doesn't happen on a fresh install, so must be an issue on our end.
