### ISSUE TITLE
Notice: Undefined index: entity in CRM_Civicase_Event_Listener_CaseTypeCategoryIsActiveToggler::shouldRun()

### ISSUE THREAD

**Issue by pbarmak** [compucorp/uk.co.compucorp.civicase#496]
When initially opening up the Civi dashboard, we get the following error multiple times:
Notice: Undefined index: entity in CRM_Civicase_Event_Listener_CaseTypeCategoryIsActiveToggler::shouldRun() (line 44 of ... /sites/default/files/civicrm/ext/uk.co.compucorp.civicase/CRM/Civicase/Event/Listener/CaseTypeCategoryIsActiveToggler.php).

**Comment by tunbola** [comment]
@pbarmak, Can you check is still a valid issue with the latest civicase? If not will close the issue soon. Thanks

**Comment by pbarmak** [comment]
> 
> 
> @pbarmak, Can you check is still a valid issue with the latest civicase? If not will close the issue soon. Thanks

I no longer see this error message on the dashboard. I am having other civicase issues, so it's a bit hard to tell if this is completely resolved. But for now, I don't see the specific error, so I'm guessing it's safe to close. Thanks.
