### ISSUE TITLE
.npmrc filename is malformed

### ISSUE THREAD

**Issue by demeritcowboy** [compucorp/uk.co.compucorp.civicase#555]
Note the `%20` at the end of the github url:

https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/.npmrc%20

This gives an error preventing cloning the repo in windows, but seems wrong anyway windows or no windows.

**Comment by deb1990** [comment]
Thanks @demeritcowboy . This has been fixed in https://github.com/compucorp/uk.co.compucorp.civicase/pull/583.
