### ISSUE TITLE
Sort order of Case Statuses matches Value, not Order/Weight

### ISSUE THREAD

**Issue by ananelson** [compucorp/uk.co.compucorp.civicase#559]
In the Overview, the Case Statuses are visualized as a Pipeline. However, the ordering of statuses does not correspond to the Order field, instead they are sorted per the Value field:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/14220/90193080-11f0da80-dd79-11ea-87f4-3757f79e59de.png">
<img width="257" alt="image" src="https://user-images.githubusercontent.com/14220/90193111-203ef680-dd79-11ea-9783-2a7c1997871f.png">

This can apparently be fixed by removing indexBy('value') below:
```js
    function getSortedCaseStatusesByName (caseStatusNames) {
      return _.chain(caseStatusNames)
        .map(function (caseStatusName) {
          return caseStatusesIndexedByName[caseStatusName];
        })
        .sortBy('weight')
        .indexBy('value') // REMOVE THIS
        .value();
    }
```

Yields correct ordering:
<img width="928" alt="image" src="https://user-images.githubusercontent.com/14220/90192873-a9a1f900-dd78-11ea-81c4-ca141bc3d20e.png">

But, I'm not sure if that's the right fix or what that might break.

**Comment by fran-compucorp** [comment]
Thanks @ananelson - I'm looking into this and will get back to you
