### ISSUE TITLE
MySQL 8 Reserved Word Issue

### ISSUE THREAD

**Issue by pbarmak** [compucorp/uk.co.compucorp.civicase#659]
In api/v3/Case/Getdetails.php, around line 290, the following query uses the "grouping" reserved word in MySQL 8. It needs to be backticked in order to work. I'm not sure if there are other MySQL 8 issues, that's just one I encountered while trying to resolve the other CiviCase issue I reported a week ago.

```
  $query = "SELECT COUNT(a.id) as count, ca.case_id
  FROM civicrm_activity a, civicrm_case_activity ca
  WHERE ca.activity_id = a.id AND a.is_current_revision = 1 AND a.is_test = 0 AND ca.case_id IN (" . implode(',', $ids) . ")
  AND a.activity_type_id IN (SELECT value FROM civicrm_option_value WHERE grouping "
  . $categoryCondition . " AND option_group_id = (SELECT id FROM civicrm_option_group WHERE name = 'activity_type'))
  " . $isOverdueCondition . "
  AND is_current_revision = 1
  AND is_deleted = 0
  AND a.status_id IN ($statusTypeIds)
  GROUP BY ca.case_id";
```

**Comment by tunbola** [comment]
Thanks @pbarmak . We'll put this in the backlog and work on it.

**Comment by tunbola** [comment]
Hi @pbarmak. Issue is fixed here: https://github.com/compucorp/uk.co.compucorp.civicase/pull/664 and should be part of the next release.
