### ISSUE TITLE
CiviCRM Core upgrade to 5.34.0 breaks CiviCase

### ISSUE THREAD

**Issue by albionbrown** [compucorp/uk.co.compucorp.civicase#721]
Using:

- Drupal 7
- CiviCRM 5.34.0
- PHP 7.1

I saw a related post ([https://github.com/compucorp/uk.co.compucorp.civicase/issues/654](https://github.com/compucorp/uk.co.compucorp.civicase/issues/654)) but I believe the issue is different. CiviCase was working ok on 5.20.0, which we were on before upgrading to 5.34.0. 

A first look at the issue presents the error:
`Error: Class name must be a valid object or a string in _civicrm_api3_basic_get() (line 1247 of
                                              /var/www/portal/sites/all/modules/contrib/civicrm/api/v3/utils.php).`

I had a step through and reached line 349 of api/v3/utils.php where it checks to see if `_civicrm_api3_case_category_instance_DAO` is a function that exists, but it isn't declared anywhere.

Does this exist in a previous version of CiviCase or is there a plan to implement it going forward?

Thanks.

**Comment by deb1990** [comment]
@albionbrown Thanks for reporting this issue. CiviCRM core from 5.31 onwards has some breaking changes, which is why we have this issue. But we are already working on this, and you can expect this to be fixed in the coming weeks.

**Comment by albionbrown** [comment]
Perfect thanks, hoping to verify soon!
