### ISSUE TITLE
Deprecated Function in CiviCase 1.14.0

### ISSUE THREAD

**Issue by pbarmak** [compucorp/uk.co.compucorp.civicase#753]
This may be a minor issue, but just to fix up. In ang/civicase.ang.php, around line 29, it is using getUrlPath(). That is now a deprecated Civi function (we receive an error on our screen). Changing it to the following (currentPath) seems to fix it:

`if (CRM_Utils_System::currentPath() == 'civicrm/case/a') {`

**Comment by james-compucorp** [comment]
Thanks for point it out @pbarmak . Will close this issue now.

**Comment by pbarmak** [comment]
@james-compucorp I just updated to 1.16, and this error is still there.

**Comment by james-compucorp** [comment]
Added to the list of things, should be fixed in 1.17 @pbarmak

**Comment by deb1990** [comment]
@pbarmak This has been fixed, and can be found in master branch now.
