### ISSUE TITLE
unable to export cases

### ISSUE THREAD

**Issue by lcdservices** [compucorp/uk.co.compucorp.civicase#757]
Conduct a search in Find Cases, select some records, and select Export. This throws a network error.:
PHP Fatal error:  require_once(): Failed opening required 'CRM/Case/Export/Form/Select.php'

**Comment by lcdservices** [comment]
go to Find Cases and conduct a search
click the checkbox and select some cases to export
select Actions > Export Cases
this results in a Network Error popup

I just ensured we were running the latest release (1.16) and it reproduces there (originally noticed in v1.14). the error is the same as noted above.

**Comment by james-compucorp** [comment]
@lcdservices I will update this thread once we do

**Comment by omarabuhussein** [comment]
This should be resolved here https://github.com/compucorp/uk.co.compucorp.civicase/pull/800 (on Civicase versions >= 2.0.0) .. though it will not work on CiviCRM versions >= 5.41.0 given that CiviCase at the moment only support CiviCRM 5.39.1.
