### ISSUE TITLE
PDF filenames should use Activity Subject?

### ISSUE THREAD

**Issue by ananelson** [compucorp/uk.co.compucorp.civicase#798]
Hi,

I am trying to get generated documents to have meaningful filenames e.g. https://lab.civicrm.org/dev/core/-/issues/2121

Per that issue/comments I believe this behavior should exist in this extension but I am not seeing it. I have just installed 1.17 version and activated it. It is not requiring an Activity Subject, nor is it using the Activity Subject to rename the filename.

I can't find the hook referenced in the original commit anywhere in the code. Did this get removed? CRM_Civicase_Hook_BuildForm_MakePdfFormSubjectRequired

**Comment by tunbola** [comment]
Hi @ananelson , the feature did not make eventually it to the civicase extension.

**Comment by ananelson** [comment]
Ok - thank you for the update.

**Comment by jamienovick** [comment]
Hi @ananelson sorry for the confusion but I think this was worked on within the extension so that users can specify the file name. Let me follow up and see where this got to. Best
