### ISSUE TITLE
CiviCRM 5.43+ compatibility: replace civicrm/activity/email/add by civicrm/case/email/add to fix case tokens in emails

### ISSUE THREAD

**Issue by mlutfy** [compucorp/uk.co.compucorp.civicase#842]
Related core change: https://github.com/civicrm/civicrm-core/commit/dcecc495e042dc45c45e23a0e02d1e02caef2341 - civicase email activity now has its own form, and that has an impact on tokens, such as `{case.subject}`.

We have been testing the extension by replacing `civicrm/activity/email/add` by `civicrm/case/email/add` and so far so good.

One reason I didn't send a PR, is that I'm not sure what this bit in `civicase_civicrm_alterMenu` does:

```
$ grep -r 'activity/email/add'
civicase.php:  $items['civicrm/activity/email/add']['ids_arguments']['json'][] = 'civicase_reload';
```

Partial fix: https://github.com/coopsymbiotic/uk.co.compucorp.civicase/commit/11fca51496d442370680ecdc6a8152527bedf239 (does not fix the tests, and the alterMenu)

**Comment by olayiwola-compucorp** [comment]
Thanks @mlutfy , this issue has now been resolved
