### ISSUE TITLE
Can't access CiviCase Dashboard

### ISSUE THREAD

**Issue by mcollopy** [compucorp/uk.co.compucorp.civicase#845]
CiviCRM 5.46.2
Shoreditch 1.0.0-beta.10
User Menu 1.0.0
CiviCase 2.6.0
Drupal 9

After installation, accessing Dashboard on the CiviCase menu generates an error:

> The website encountered an unexpected error. Please try again later.
> 
> InvalidArgumentException: The user-entered string 'https://dev.audienceware.com.au/civicrm/case/a/?case_type_category=1#/case?case_type_category=1' must begin with a '/', '?', or '#'. in Drupal\Core\Url::fromUserInput() (line 214 of core/lib/Drupal/Core/Url.php).

This appears to be a previous attempt at a workaround, but hacky:
https://lab.civicrm.org/dev/core/-/issues/2651

Note this is in addition to the previously reported error - the only reason I got this far was by dsiabling the dependency:
https://github.com/compucorp/uk.co.compucorp.usermenu/issues/13

**Comment by Akenward** [comment]
I'm getting the same problem.  Every option on the "Cases" menu crashes with this error except for "Case reports" of which there are none.

**Comment by mcollopy** [comment]
CiviCase and CiviProspect installed successfully fresh Drupal 9 instance and CiviCRM 5.59.2
- however viewing the CiviCase or CiviProspect dashboard with error
"The website encountered an unexpected error. Please try again later."

Watchdog provides more details https://test.audienceware.com/admin/reports/dblog/event/129
InvalidArgumentException: The user-entered string 'https://test.audienceware.com/civicrm/case/a/?case_type_category=1#/case?case_type_category=1' must begin with a '/', '?', or '#'. in Drupal\Core\Url::fromUserInput() (line 216 of /var/www/test/web/core/lib/Drupal/Core/Url.php).

This is the same problem as before - here are some links which may help
https://www.drupal.org/project/page_manager/issues/2909040
https://drupal91.rssing.com/chan-8130804/all_p4651.html
https://lab.civicrm.org/dev/core/-/issues/2651

**Comment by olayiwola-compucorp** [comment]
Closing this issue, it should be resolved by now.
