### ISSUE TITLE
Ambiguous compatibility infos in info.xml

### ISSUE THREAD

**Issue by niels-heinemann** [compucorp/uk.co.compucorp.civicase#904]
I do not know if I may install this extension in vanilla civicrm 5.51. Your info.xml states

     <compatibility>
        <ver>5.51</ver>
      </compatibility>
      <comments>
        Supported CiviCRM versions  :
        - A patched version of CiviCRM 5.39.1 (Download link: https://github.com/compucorp/civicrm-core/releases/download    /5.39.1%2Bpatch.76dd32/civicrm-5.39.1+patch.76dd32.tar.gz)
      </comments>

**Comment by olayiwola-compucorp** [comment]
Thanks, @niels-heinemann, this will be corrected. 5.51 is the supported version

**Comment by yashodha** [comment]
@olayiwola-compucorp  Can you point to me to the commit in CiviCRM 5.51 where this was merged? Thanks!

**Comment by olayiwola-compucorp** [comment]
Hi @yashodha, see here https://github.com/compucorp/uk.co.compucorp.civicase/commit/b02337a6b9e8aefcdb12229cd4b520dc2fad19f1
